import Head from 'next/head'
import {Layout} from "@components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        Main Content

        <div className="max-w-xl mx-auto border border-gray-300 rounded-lg shadow overflow-hidden hover:shadow-lg my-8">
          <div className="bg-gray-800 text-blue-300 px-4 py-3 border-b">
            <h2 className="font-bold text-3xl">Next.js Boilerplate</h2>
          </div>
          <div className="p-4 text-gray-500 flex flex-col gap-y-4">
            <ul className="list-disc list-inside">
              <li>Typescript & ESLint</li>
              <li>Tailwind CSS</li>
              <li>Storybook</li>
            </ul>

            <hr />

            <p>Start editing right away!</p>
          </div>
          <div className="px-4 py-2 text-center bg-gray-800 text-gray-200 border-t">
            Leave a ⭐{'  '} on <a href="https://github.com/Kyoss79/next-ts-tw-sb-boilerplate" target="_blank" rel="noreferrer" className="border-b">github</a>!
          </div>
        </div>
      </Layout>
    </>
  )
}
